import { Header } from "@/components/Header";
import { Button } from "@/components/ui/button";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Coffee",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header></Header>
      <div className=" mx-20 my-11">
        <div className="flex">
          <Link href="/home">
            <Button
              variant="outline"
              className="w-[250px] h-9 pr-45 border-none "
            >
              <p className="">Home</p>
            </Button>
          </Link>
        </div>
        <div>
          <Link href="/explore">
            <Button
              variant="outline"
              className="w-[250px] h-9 pr-43 border-none "
            >
              <p className="">Explore</p>
            </Button>
          </Link>
        </div>
        <div>
          <Link href="/view-page">
            <Button
              variant="outline"
              className="w-[250px] h-9 pr-38 border-none "
            >
              <p className="">View page</p>
            </Button>
          </Link>
        </div>
        <div>
          <Link href="/account-settings">
            <Button
              variant="outline"
              className="w-[250px] h-9 pr-27 border-none "
            >
              <p className="">Account settings</p>
            </Button>
          </Link>
        </div>
        {children}
      </div>
    </div>
  );
}
