import { Header } from "@/components/Header";
import { Button } from "@/components/ui/button";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Coffee",
  description: "Generated by create next app",
};

const sidebarItems = [
  {
    title: "Home",
    href: "/home",
  },
  {
    title: "Explore",
    href: "/explore",
  },
  {
    title: "View page",
    href: "/view-page",
  },
  {
    title: "Account Settings",
    href: "/account-settings",
  },
];

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="flex justify-center gap-20 2xl:gap-50">
        <div className="">
          {sidebarItems.map(({ title, href }, index) => (
            <div key={index}>
              <Link href={href}>
                <Button
                  variant="outline"
                  className="w-[250px] h-9  border-none flex justify-start items-center"
                >
                  <p className=" ">{title}</p>
                </Button>
              </Link>
            </div>
          ))}
        </div>
        <div>{children}</div>
      </div>
    </div>
  );
}
